// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhrvrD6LMwdJ3jilzrWzVaUgnR8psDP-s',
    appId: '1:160286330117:android:9f31b7813744265c0abb6c',
    messagingSenderId: '160286330117',
    projectId: 'bobberv1-ec028',
    storageBucket: 'bobberv1-ec028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQB6EgvIH10RNWpa0iVPQIbc4uiOLyOY',
    appId: '1:160286330117:ios:86b87587684cec4a0abb6c',
    messagingSenderId: '160286330117',
    projectId: 'bobberv1-ec028',
    storageBucket: 'bobberv1-ec028.appspot.com',
    iosBundleId: 'com.example.bobberv1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOnk6NV7yufLOOmL1xIIEhPr6I8SX72Wo',
    appId: '1:160286330117:web:a5fbc696bde5e7fc0abb6c',
    messagingSenderId: '160286330117',
    projectId: 'bobberv1-ec028',
    authDomain: 'bobberv1-ec028.firebaseapp.com',
    storageBucket: 'bobberv1-ec028.appspot.com',
    measurementId: 'G-2GEHF64DGC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmQB6EgvIH10RNWpa0iVPQIbc4uiOLyOY',
    appId: '1:160286330117:ios:f0d8793d697597860abb6c',
    messagingSenderId: '160286330117',
    projectId: 'bobberv1-ec028',
    storageBucket: 'bobberv1-ec028.appspot.com',
    iosBundleId: 'com.example.bobber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOnk6NV7yufLOOmL1xIIEhPr6I8SX72Wo',
    appId: '1:160286330117:web:55804083cfd232980abb6c',
    messagingSenderId: '160286330117',
    projectId: 'bobberv1-ec028',
    authDomain: 'bobberv1-ec028.firebaseapp.com',
    storageBucket: 'bobberv1-ec028.appspot.com',
    measurementId: 'G-ZH24M3YFPD',
  );

}